---
# file: roles/cluster/tasks/metallb.yml
- name: Add metallb Helm charts repository
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: https://metallb.github.io/metallb
  become: false

- name: Deploy metallb chart using set values on target
  kubernetes.core.helm:
    release_name: metallb
    chart_ref: metallb/metallb
    chart_version: "0.15.*"
    release_namespace: kube-system
    update_repo_cache: true
    wait: true
    atomic: true
  become: false

- name: Create a metallb AddressPool config
  kubernetes.core.k8s:
    state: present
    template: metallb-addresspool.yml.j2
  register: result
  become: false
