---
# file: roles/cluster/tasks/metrics-server.yml
- name: Add metrics-server Helm charts repository
  kubernetes.core.helm_repository:
    name: metrics-server
    repo_url: https://kubernetes-sigs.github.io/metrics-server/
  become: false

- name: Deploy metrics-server chart on target
  kubernetes.core.helm:
    release_name: metrics-server
    chart_ref: metrics-server/metrics-server
    chart_version: "3.13.*"
    release_namespace: kube-system
    update_repo_cache: true
    wait: true
    atomic: true
  become: false
