apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns
  namespace: dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dns-exec
  namespace: dns
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/status"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dns
  namespace: dns
subjects:
  - kind: ServiceAccount
    name: dns
    namespace: dns
roleRef:
  kind: Role
  name: dns-exec
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dns-cronjob
  namespace: dns
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  timeZone: Asia/Tokyo
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: dns
          containers:
            - name: kubectl
              image: ghcr.io/akashisn/kubectl@sha256:a1ba6129255f5396b811ea428c16a5a8dea3f21e4d69a2ce412455d36777262b
              imagePullPolicy: IfNotPresent
              args:
                [
                  "rollout",
                  "-n",
                  "dns",
                  "restart",
                  "deployments/dns-server"
                ]
          restartPolicy: Never
