apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsmasq-conf
  namespace: dns
data:
  dnsmasq.conf: |
    port=10053
    cache-size=0
    no-resolv
    server=1.0.0.1
    server=1.1.1.1
    strict-order
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsdist-conf
  namespace: dns
data:
  dnsdist.conf: |
    setACL("0.0.0.0/0")
    addACL("::/0")
    newServer("127.0.0.1:10053")
    addLocal("0.0.0.0:53")
    addLocal("[::]:53")
    addDOHLocal("0.0.0.0:443", "/certs/tls.crt", "/certs/tls.key", "/")
    addDOHLocal("[::]:443", "/certs/tls.crt", "/certs/tls.key", "/")
    addTLSLocal("0.0.0.0:853", "/certs/tls.crt", "/certs/tls.key")
    addTLSLocal("[::]:853", "/certs/tls.crt", "/certs/tls.key")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-server
  namespace: dns
spec:
  selector:
    matchLabels:
      app: dns-server
  replicas: 4
  template:
    metadata:
      labels:
        app: dns-server
    spec:
      containers:
        - name: dnsmasq
          image: ghcr.io/akashisn/dnsmasq@sha256:b6645721de285ba41bd34b88e0627d54094e69609a95912b5160af8819a4a756
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: dnsmasq-conf
              mountPath: /etc/dnsmasq.d/dnsmasq.conf
              subPath: dnsmasq.conf
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
        - name: dnsdist
          image: ghcr.io/akashisn/dnsdist@sha256:ef56cad0685803452cd9521a2ecea787cf6662f09731380ae992894c681cc6c0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 53
              protocol: UDP
              name: dnsdist
            - containerPort: 443
              protocol: TCP
              name: dnsdist-doh
            - containerPort: 853
              protocol: TCP
              name: dnsdist-dot
          volumeMounts:
            - name: dnsdist-conf
              mountPath: /etc/dnsdist.conf
              subPath: dnsdist.conf
              readOnly: true
            - name: certs
              mountPath: /certs
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
      volumes:
        - name: certs
          secret:
            secretName: dns-cert
        - name: dnsmasq-conf
          configMap:
            name: dnsmasq-conf
        - name: dnsdist-conf
          configMap:
            name: dnsdist-conf
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: dns-pool
  labels:
    service: dns-server
  name: dns-server
  namespace: dns
spec:
  type: LoadBalancer
  ports:
    - port: 53
      protocol: UDP
      name: dnsdist
    - port: 853
      protocol: TCP
      name: dnsdist-dot
  selector:
    app: dns-server
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: dns-pool
  labels:
    service: dns-server-doh
  name: dns-server-doh
  namespace: dns
spec:
  type: ClusterIP
  ports:
    - port: 443
      protocol: TCP
      name: dnsdist-doh
  selector:
    app: dns-server
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dns-cert
  namespace: dns
spec:
  secretName: dns-cert
  dnsNames:
    - dns.akashisn.info
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-dns-server
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPCS"
  namespace: dns
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dns.akashisn.info
      secretName: dns-cert
  rules:
    - host: dns.akashisn.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dns-server-doh
                port:
                  name: dnsdist-doh
