apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: immich-microservices
  name: immich-microservices
  namespace: immich
spec:
  selector:
    matchLabels:
      app: immich-microservices
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  replicas: 2
  template:
    metadata:
      labels:
        app: immich-microservices
    spec:
      containers:
        - name: immich-microservices
          image: ghcr.io/immich-app/immich-server:v2.5.6
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: immich-env
          env:
            - name: IMMICH_WORKERS_EXCLUDE
              value: api
          volumeMounts:
            - name: immich-photos
              mountPath: /data
            - name: immich-secrets
              mountPath: /secrets
          startupProbe:
            exec:
              command:
              - immich-healthcheck
            periodSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
              - immich-healthcheck
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
              - immich-healthcheck
            periodSeconds: 30
      volumes:
        - name: immich-secrets
          projected:
            sources:
              - secret:
                  name: immich-secrets
        - name: immich-photos
          persistentVolumeClaim:
            claimName: immich-photos-pvc
