apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: immich-postgres
  name: immich-postgres
  namespace: immich
spec:
  replicas: 1
  serviceName: immich-postgres
  selector:
    matchLabels:
      app: immich-postgres
  template:
    metadata:
      labels:
        app: immich-postgres
    spec:
      containers:
        - name: immich-postgres
          image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: TZ
              value: Asia/Tokyo
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD_FILE
              value: /secrets/immich_postgres_user_password
            - name: POSTGRES_DB
              value: immich
            - name: POSTGRES_INITDB_ARGS
              value: "--data-checksums"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: immich-secrets
              mountPath: /secrets
          startupProbe:
            exec:
              command:
              - /usr/local/bin/healthcheck.sh
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            exec:
              command:
              - /usr/local/bin/healthcheck.sh
            periodSeconds: 300
          livenessProbe:
            exec:
              command:
              - /usr/local/bin/healthcheck.sh
            periodSeconds: 300
      volumes:
        - name: immich-secrets
          secret:
            secretName: immich-secrets
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOncePod
        storageClassName: local-storage
        resources:
          requests:
            storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: immich-postgres
  name: immich-postgres
  namespace: immich
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    app: immich-postgres
