---
# file: roles/cluster/tasks/argo-cd.yml
- name: Add argo Helm charts repository
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm
  become: false

- name: Deploy argocd chart using set values on target
  kubernetes.core.helm:
    release_name: argo-cd
    chart_ref: argo/argo-cd
    release_namespace: argo-cd
    create_namespace: true
    update_repo_cache: true
    wait: true
    atomic: true
    values: "{{ lookup('template', 'argo-cd-values.yml.j2') | from_yaml }}"
  become: false

- name: Create the argo-cd/Application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'manifests/application.yml') | from_yaml }}"
  become: false
