---
# file: roles/common/tasks/watchdog.yml
- name: Install watchdog
  ansible.builtin.apt:
    name:
      - watchdog
    state: present
    update_cache: true
  become: true

- name: Update start timeout in systemd.conf
  ansible.builtin.replace:
    path: /etc/systemd/system.conf
    regexp: '#DefaultTimeoutStartSec=90s'
    replace: 'DefaultTimeoutStartSec=90s'
  become: true

- name: Update shutdown timeout in systemd.conf
  ansible.builtin.replace:
    path: /etc/systemd/system.conf
    regexp: '#DefaultTimeoutStopSec=90s'
    replace: 'DefaultTimeoutStopSec=90s'
  become: true

- name: Update abort timeout in systemd.conf
  ansible.builtin.replace:
    path: /etc/systemd/system.conf
    regexp: '#DefaultTimeoutAbortSec=90s'
    replace: 'DefaultTimeoutAbortSec=90s'
  become: true

- name: Update start timeout in user.conf
  ansible.builtin.replace:
    path: /etc/systemd/user.conf
    regexp: '#DefaultTimeoutStartSec=90s'
    replace: 'DefaultTimeoutStartSec=90s'
  become: true

- name: Update shutdown timeout in user.conf
  ansible.builtin.replace:
    path: /etc/systemd/user.conf
    regexp: '#DefaultTimeoutStopSec=90s'
    replace: 'DefaultTimeoutStopSec=90s'
  become: true

- name: Update abort timeout in user.conf
  ansible.builtin.replace:
    path: /etc/systemd/user.conf
    regexp: '#DefaultTimeoutAbortSec=90s'
    replace: 'DefaultTimeoutAbortSec=90s'
  become: true

- name: Just force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Enable and start watchdog service
  ansible.builtin.systemd:
    name: watchdog
    state: started
    enabled: true
    daemon_reload: true
  become: true

- name: Run sync
  ansible.builtin.command:
    cmd: sync
  become: true
